apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recommendation-system
  namespace: recommendation-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recommendation-system
    spec:
      containers:
        - name: recommendation-system
          image: java:8
          command: ["java", "-jar", "java/recommendation-system.jar"]
          volumeMounts:
          - mountPath: "/java"
            name: code
            subPath: recommendation-system/recommendation-system
          - mountPath: "/etc/localtime"
            name: tz-config
          ports:
            - containerPort: 8080
          env:
            - name: zk_root
              value: '/config-center/'
            - name: zk_servers
              value: 'zookeeper-standalone.platform:2181'
            - name: secret_key
              value: '123456'
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: pvc-recommendation-system
        - name: tz-config
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-system
  namespace: recommendation-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: recommendation-system
